name: Blinded
version: ${project.version}
main: com.example.economia.EconomiaPlugin
api-version: "1.21"
author: "crazy"
description: "Plugin de economia com menus visuais e integração Bedrock (Geyser/Floodgate)."
softdepend: [Geyser-Spigot, floodgate]
commands:
  money:
    description: Comandos de economia
    aliases: [saldo, coins]
    usage: /money <saldo|pay|set|add|take>
  painel:
    description: Abre o painel principal
    aliases: [menu]
    usage: /painel
  login:
    description: Abre o painel de login
    usage: /login
  register:
    description: Abre o painel de registro
    usage: /register
  loja:
    description: Abre a loja do servidor
    usage: /loja
  multa:
    description: Gerenciar multas (admin)
    usage: /multa add <jogador> <valor> <motivo>
  blinded:
    description: Atualizacoes do plugin
    usage: /blinded <check|download>
  painel_admin:
    description: Abre o painel administrativo
    usage: /painel_admin
    aliases: [admin]
  ping:
    description: Mostra seu ping atual
    usage: /ping
  anuncio:
    description: Envia um anuncio global
    usage: /anuncio <mensagem>
    permission: blinded.admin
  sethome:
    description: Define um home
    usage: /sethome [nome]
  home:
    description: Teleporta para um home
    usage: /home [nome]
  delhome:
    description: Deleta um home
    usage: /delhome [nome]
  homes:
    description: Lista seus homes
    usage: /homes
  vender:
    description: Lista um item no mercado
    usage: /vender <preco>
  mercado:
    description: Abre o mercado de jogadores
    usage: /mercado
  shopvip:
    description: Abre a loja VIP do servidor
    usage: /shopvip
    aliases: [lojavip, servershop]
  venda:
    description: Vende o item na mão
    usage: /venda
    aliases: [sell, vendermao]
  upgrade:
    description: Evolui o item na mão (gasta XP)
    usage: /upgrade
    aliases: [melhorar, upar]
  evoluir:
    description: Transforma diamante em netherite (gasta 1 level XP)
    usage: /evoluir
    aliases: [evolve, netherite]
  tag:
    description: Define tag de um jogador (admin)
    usage: /tag <player> <tag>
    permission: blinded.admin
permissions:
  blinded.admin:
    description: Permite administrar o saldo dos jogadores.
    default: op
  blinded.treefeller:
    description: Permite cortar arvore inteira (agachado + machado).
    default: true
  blinded.tag.vip:
    description: Tag VIP
    default: false
  blinded.tag.mvp:
    description: Tag MVP
    default: false
  blinded.tag.elite:
    description: Tag Elite
    default: false
  blinded.tag.legend:
    description: Tag Lenda
    default: false
  blinded.tag.admin:
    description: Tag Admin
    default: op
  blinded.tag.mod:
    description: Tag Mod
    default: false
  blinded.tag.helper:
    description: Tag Helper
    default: false
  blinded.tag.builder:
    description: Tag Builder
    default: false
  blinded.tag.youtuber:
    description: Tag Youtuber
    default: false
